### ISSUE TITLE
Deployment thru Flux failing

### ISSUE THREAD

**Issue by aubernknight** [gimlet-io/capacitor#107]
I followed directions exactly as they existed. Deployment failed as a capacitor was created and immediately deleted. Do you have any thoughts?

1s	Normal	Progressing	Kustomization/capacitor	Kustomization/flux-system/capacitor configured
  	      	           	                       	OCIRepository/flux-system/capacitor created
0s	Normal	ReconciliationSucceeded	Kustomization/capacitor	Reconciliation finished in 563.060082ms, next run in 10m0s
0s	Normal	NewArtifact	OCIRepository/capacitor	stored artifact with revision 'v0.4.2@sha256:1e72940be8383cd5054e3efcff8ec36f27e33959a4b940fc4b956c932083578b' from 'oci://ghcr.io/gimlet-io/capacitor-manifests', origin source 'git://github.com/gimlet-io/capacitor.git', origin revision 'capacitor-v0.4.2@sha1:d8c8bc95c5af71ddf8baabc71da744dde9dcbc0c'
0s	Normal	Progressing	Kustomization/capacitor	ServiceAccount/flux-system/capacitor created
  	      	           	                       	ClusterRole/capacitor created
  	      	           	                       	ClusterRoleBinding/capacitor created
  	      	           	                       	Service/flux-system/capacitor created
  	      	           	                       	Deployment/flux-system/capacitor created
0s	Normal	GarbageCollectionSucceeded	OCIRepository/capacitor	garbage collected artifacts for deleted resource
0s	Normal	Progressing	Kustomization/capacitor	OCIRepository/flux-system/capacitor deleted
  	      	           	                       	Kustomization/flux-system/capacitor deleted
0s	Normal	Progressing	Kustomization/capacitor	Health check passed in 5.221377515s
0s	Normal	ReconciliationSucceeded	Kustomization/capacitor	Reconciliation finished in 5.579574302s, next run in 30m0s
0s	Normal	ReconciliationSucceeded	Kustomization/capacitor	Deployment/flux-system/capacitor deleted
  	      	                       	                       	Service/flux-system/capacitor deleted
  	      	                       	                       	ClusterRoleBinding/capacitor deleted
  	      	                       	                       	ClusterRole/capacitor deleted
  	      	                       	                       	ServiceAccount/flux-system/capacitor deleted
0s	Normal	ReconciliationSucceeded	Kustomization/capacitor	Reconciliation finished in 517.575176ms, next run in 30m0s

**Comment by laszlocph** [comment]
Wow, maybe you have a race condition between kustomizations?
One has it, the other does not, and it deletes it immediately?

**Comment by aubernknight** [comment]
Found the health check is failing

**Comment by aubernknight** [comment]
Set prune to false and was able to describe the pod and found the following: 

Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  2m48s  default-scheduler  Successfully assigned flux-system/capacitor-XXXXX-XXXXX to ip-10-X-X-53.X-west-2.compute.internal
  Normal   Pulled     2m47s  kubelet            Container image "ghcr.io/gimlet-io/capacitor:v0.4.2" already present on machine
  Normal   Created    2m47s  kubelet            Created container capacitor
  Normal   Started    2m47s  kubelet            Started container capacitor
  Warning  Unhealthy  2m47s  kubelet            Readiness probe failed: Get "http://10.X.X.134:9000/": dial tcp 10.X.X.134:9000: connect: connection refused


And this from the pod:
/capacitor $ netstat -tulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
TCP        0      0 :::9000                 :::*                    LISTEN      1/capacitor
/capacitor $ 
/capacitor $ ifconfig
eth0      Link encap: Ethernet  HWaddr XX:XX:XX:XX: XX:67  
          init addr:10.X.X.134  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:45908 errors:0 dropped:0 overruns:0 frame:0
          TX packets:55434 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:156511699 (149.2 MiB)  TX bytes:5370200 (5.1 MiB)

lo        Link encap: Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 add: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

/capacitor $
