### ISSUE TITLE
Feature Request: Multi-Arch Support

### ISSUE THREAD

**Issue by 1Solon** [gimlet-io/capacitor#115]
Hey guys, I like the look of capacitor.

I'd love to run this on my arm64-based cluster but I realised the provided containers are built only for amd64.

Would it be possible to build for multiple architectures?

Thanks!

**Comment by laszlocph** [comment]
We are built for arm64 as well: https://github.com/orgs/gimlet-io/packages/container/capacitor/203687632?tag=v0.4.2

<img width="759" alt="image" src="https://github.com/user-attachments/assets/253f9978-1cdc-4823-b10f-cdd24f17018c">

Am I missing something?
