### ISSUE TITLE
Error Installing Capacitor with Older Flux Version: Missing API Resource Errors

### ISSUE THREAD

**Issue by PraneethMM** [gimlet-io/capacitor#116]
I'm trying to install Capacitor on Kubernetes using an older version of Flux, but I encounter the following error:

```
level=error msg="capacitor requires source.toolkit.fluxcd.io/v1: the server could not find the requested res
ource"                                                                                                                                  
level=error msg="capacitor requires kustomize.toolkit.fluxcd.io/v1: the server could not find the requested 
resource"   
```

Our current API versions for Flux resources are:
- kustomize.toolkit.fluxcd.io/v1beta2
- source.toolkit.fluxcd.io/v1beta2

**Comment by laszlocph** [comment]
I believe `kustomize.toolkit.fluxcd.io/v1` and `source.toolkit.fluxcd.io/v1` was introduced in Flux [v2](https://github.com/fluxcd/flux2/releases/tag/v2.0.0). We don't want to support Flux version prior to v2.
