### ISSUE TITLE
Run as non-root/non privileged

### ISSUE THREAD

**Issue by TheKangaroo** [gimlet-io/capacitor#117]
I cannot start the capacitor container as described in the README because we do not allow root or escalated privileges.
I don't think it's necessary for capacitor to have the ability to escalate privileges or run as root, but I couldn't find a way to change the securityContext of the deployment either.

It would be super useful to have these things disabled by default in the deployment if there is no need for root and privileges.

I've seen that the helm chart by @sebastiangaiser in #84 allows you to set the securityContext, is this something you plan to move forward with and integrate the helm chart into this repo?

**Comment by laszlocph** [comment]
https://github.com/gimlet-io/capacitor/pull/111 May be a fix for this? Try version 0.4.3
