### ISSUE TITLE
Capacitor UI not rendering issue loading manifest.json

### ISSUE THREAD

**Issue by nralbers** [gimlet-io/capacitor#129]
After latest release, getting the following error on the main screen of the UI

Something went wrong:

Cannot read properties of undefined (reading 'spec')

### developer console is showing the following:
![{0B63751A-C079-4933-9FEF-A5545F10ECAE}](https://github.com/user-attachments/assets/a34b81ef-5c39-4bf4-933f-9fed701ca609)

Failed to load resource: the server responded with a status of 401 () manifest.json
 Manifest: Line: 1, column: 5, Unexpected data after root element.
TypeError: Cannot read properties of undefined (reading 'spec')
    at om (index-CPzofljc.js:64:46518)
    at Wl (index-CPzofljc.js:38:16998)
    at gp (index-CPzofljc.js:40:43963)
    at mp (index-CPzofljc.js:40:39727)
    at Cg (index-CPzofljc.js:40:39655)
    at Fs (index-CPzofljc.js:40:39508)
    at tl (index-CPzofljc.js:40:35875)
    at fp (index-CPzofljc.js:40:34826)
    at E (index-CPzofljc.js:25:1565)
    at MessagePort.X (index-CPzofljc.js:25:1928)

**Comment by nralbers** [comment]
After pinning to a specific version, I can confirm that the UI is broken in different ways in versions 0.4.4. and 0.4.5. Version 0.4.3 seems to be functioning correctly.

**Comment by nralbers** [comment]
After further testing, 0.4.3 also has issues: the bottom bar with Sources, Kustomizations and Helm Releases is no longer folding out.

**Comment by laszlocph** [comment]
About 0.4.5 and manifest.json:

Something returns 401 on the manifest.json file.
Capacitor never returns 401. Do you access it through a proxy or ingress?
Does it behave the same way when you access it via port-forward? `kubectl port-forward svc/capacitor 9000:9000 -n flux-system`
