### ISSUE TITLE
can we use capacitor to crud objects of flux-cd in the future?

### ISSUE THREAD

**Issue by denglouping** [gimlet-io/capacitor#76]
I tried capacitor, it does help me to know the situations about my helmreleases, but i didn't find where to create a new helmrelease or edit it.

**Comment by laszlocph** [comment]
That feels a bit against gitops. If Capacitor would directly create these resources.

If Capacitor would write git. That is a whole new ballpark of complexity and scope.

I would say this is not in scope for Capacitor.
But future may prove me wrong.
