### ISSUE TITLE
Looking for Flux version compatibility information

### ISSUE THREAD

**Issue by marians** [gimlet-io/capacitor#77]
What Flux version is required for Capacitor? It would be great to find this information in the README.

I tried adding the `OCIRepository` resource described in the README to a cluster and got as a result:

> error: error validating "capacitor.yaml": error validating data: ValidationError(OCIRepository.spec.verify): unknown field "matchOIDCIdentity" in io.fluxcd.toolkit.source.v1beta2.OCIRepository.spec.verify

The according key `matchOIDCIdentity` has been introduced to the OCIRepository CRD in https://github.com/fluxcd/flux2/releases/tag/v2.2.0

Apart from that identity verification, it would be nice to know if Capacitor relied on any Flux version specific features.

**Comment by laszlocph** [comment]
Thanks for the report.

The field in question was introduced in Flux v2.2.0. (source-controller v1.2.0), but it is not a mandatory thing. Just if someone wants to enable cosign based signature verification.

In general Capacitor requires Flux v2.0.0.
Made https://github.com/gimlet-io/capacitor/pull/79 to:
- display compatibility note
- and making cosign optional

Hope this helps. Now I removed the cosign part from the yaml. You can retry.
