### ISSUE TITLE
Broken UI [BUG]

### ISSUE THREAD

**Issue by SorsOps** [gimlet-io/capacitor#88]
After the 0.4.0 update I see additional sources now listed in the UI which I presume are the new helm charts and repos, however 4 of them are listed being in some kind of error state

![image](https://github.com/gimlet-io/capacitor/assets/80043879/668fa917-98c8-4978-99ac-b9ce82ba6a08)

Clicking on Sources breaks the UI and displays an empty white screen. Looks like something is supposed to have some kind of timestamp that is not there which causes the entire UI to break. Seems like there needs to be an error boundary to prevent this from crashing the entire thing as well as something to prevent the initial error

[capacitor.tiamarch.xyz-1712687695144.log](https://github.com/gimlet-io/capacitor/files/14922702/capacitor.tiamarch.xyz-1712687695144.log)

Looks like the problem line is here https://github.com/gimlet-io/capacitor/blob/fc6c8ec6d4ee30d39f43b57b9cb17e996313a750/web/src/ReadyWidget.jsx#L16

**Comment by ubergesundheit** [comment]
I dug a little into the code and runtime of the web UI and I think its related to Sources having an empty (`{}`) `.status` field. I have some `HelmRepositories` pointing at oci repositories that have this kind of empty `.status` field. The code you linked tries to parse the non-existant conditions but then fails.

**Comment by stefanprodan** [comment]
@laszlocph we need to support empty status for HelmRepo `type: oci`, this is a change in Flux v2.2

**Comment by laszlocph** [comment]
Appreciate all the context @SorsOps @ubergesundheit @stefanprodan. Indeed the empty status for OCI HelmRepositories broke it. Pushed a fix and released in https://github.com/gimlet-io/capacitor/releases/tag/capacitor-v0.4.1
